# Generated by Django 5.2.14 on 2026-06-02 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('host_session_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('playing', 'Playing'), ('finished', 'Finished')], default='lobby', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('music_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.musicset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gamesession')),
            ],
            options={
                'ordering': ['session', '-score', 'joined_at'],
                'constraints': [models.UniqueConstraint(fields=('session', 'name'), name='unique_player_name_per_session')],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('offset_ms', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gamesession')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.track')),
            ],
            options={
                'ordering': ['session', 'index'],
                'constraints': [models.UniqueConstraint(fields=('session', 'index'), name='unique_round_index_per_session'), models.UniqueConstraint(fields=('session', 'track'), name='unique_track_per_session')],
            },
        ),
    ]
