# Generated by Django 5.2.14 on 2026-06-05 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='answer_options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='round',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_artist', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.round')),
            ],
            options={
                'ordering': ['round', 'submitted_at', 'player'],
                'constraints': [models.UniqueConstraint(fields=('round', 'player'), name='unique_answer_per_round_player')],
            },
        ),
    ]
