# Generated by Django 5.2.14 on 2026-06-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_round_answer_options_round_deadline_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='round',
            name='unique_track_per_session',
        ),
    ]
