# Generated by Django 5.2.14 on 2026-05-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=22)),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('duration_ms', models.IntegerField()),
                ('music_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.musicset')),
            ],
            options={
                'ordering': ['music_set', 'artist', 'title'],
                'unique_together': {('music_set', 'spotify_track_id')},
            },
        ),
    ]
